import type { AgentActivity } from './types';

const activities: AgentActivity[] = [
  // --- Weekly Social Media ---
  {
    id: 'act-1',
    agentId: 'weekly-social-media',
    description: 'Published 7 posts across Instagram and Facebook',
    detail: '3 carousels, 2 reels, 2 static posts — all scheduled for optimal engagement windows',
    status: 'completed',
    creditsUsed: 15,
    timestamp: '2026-03-10T09:00:00Z',
  },
  {
    id: 'act-2',
    agentId: 'weekly-social-media',
    description: 'Researched trending home service topics for this week',
    detail: 'Top trending: spring cleaning tips, before/after transformations, eco-friendly products',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-10T08:30:00Z',
  },
  {
    id: 'act-3',
    agentId: 'weekly-social-media',
    description: 'Generated 5 carousel images for next week\'s posts',
    status: 'needs-approval',
    creditsUsed: 5,
    timestamp: '2026-03-10T10:15:00Z',
    contentPreviews: [
      {
        title: 'Kitchen Remodel B&A',
        caption: 'Transform your space this spring — swipe to see the before & after of the Johnson kitchen remodel...',
        platform: 'Instagram',
        scheduledLabel: 'Mon 10am',
        color: '#e8d5b7',
        image: '/previews/kitchen-remodel.jpg',
      },
      {
        title: 'Spring Cleaning List',
        caption: 'Your ultimate spring cleaning checklist is here! Save this post and tackle one room at a time...',
        platform: 'Facebook',
        scheduledLabel: 'Tue 10am',
        color: '#b7d8c5',
        image: '/previews/spring-cleaning.jpg',
      },
      {
        title: 'Client Spotlight',
        caption: 'Nothing makes our day like happy clients. Hear what the Ramirez family had to say about their bathroom renovation...',
        platform: 'Instagram',
        scheduledLabel: 'Wed 10am',
        color: '#c5d4e8',
        image: '/previews/client-spotlight.jpg',
      },
      {
        title: 'Eco-Friendly Guide',
        caption: 'Going green at home doesn\'t have to be hard. Here are 5 eco-friendly swaps our team recommends...',
        platform: 'Facebook',
        scheduledLabel: 'Thu 10am',
        color: '#d4e8c5',
        image: '/previews/eco-friendly.jpg',
      },
      {
        title: 'Meet the Team',
        caption: 'Behind every great project is an even greater team. Get to know the people who make it happen...',
        platform: 'Instagram',
        scheduledLabel: 'Fri 10am',
        color: '#e0d0e8',
        image: '/previews/meet-the-team.jpg',
      },
    ],
  },

  // --- Review Collector ---
  {
    id: 'act-4',
    agentId: 'review-collector',
    description: 'Sent review request to Sarah Johnson after her appointment',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-10T11:20:00Z',
  },
  {
    id: 'act-5',
    agentId: 'review-collector',
    description: 'Sarah Johnson left a 5-star review on Google',
    detail: '"Amazing service, will definitely be back! The team was so professional."',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-10T14:45:00Z',
  },
  {
    id: 'act-6',
    agentId: 'review-collector',
    description: 'Sent follow-up reminder to Mike Chen for pending review',
    status: 'completed',
    creditsUsed: 1,
    timestamp: '2026-03-09T16:00:00Z',
  },
  {
    id: 'act-7',
    agentId: 'review-collector',
    description: 'Flagged negative feedback from Tom Wilson for your attention',
    status: 'needs-approval',
    creditsUsed: 1,
    timestamp: '2026-03-09T13:30:00Z',
    preview: [
      { label: 'Client', value: 'Tom Wilson — first visit on March 8' },
      { label: 'Rating', value: '2 out of 5 stars' },
      { label: 'Feedback', value: '"Service was fine but I waited 45 minutes past my appointment time. Not great for a first visit."' },
      { label: 'Suggested action', value: 'Send a private apology for the wait and offer 20% off his next visit before the review goes public.' },
    ],
  },

  // --- Appointment Reminder ---
  {
    id: 'act-8',
    agentId: 'appointment-reminder',
    description: 'Sent 24h reminder to Lisa Park for tomorrow at 10am',
    status: 'completed',
    creditsUsed: 2,
    timestamp: '2026-03-10T10:00:00Z',
  },
  {
    id: 'act-9',
    agentId: 'appointment-reminder',
    description: 'Mike Chen confirmed his appointment for Thursday',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-10T09:45:00Z',
  },
  {
    id: 'act-10',
    agentId: 'appointment-reminder',
    description: 'Filled cancelled 2pm slot — booked Amy Davis from waitlist',
    status: 'completed',
    creditsUsed: 2,
    timestamp: '2026-03-09T14:10:00Z',
  },
  {
    id: 'act-11',
    agentId: 'appointment-reminder',
    description: 'Sent 2h reminders to 3 clients with afternoon appointments',
    status: 'completed',
    creditsUsed: 2,
    timestamp: '2026-03-09T11:00:00Z',
  },

  // --- Client Intake ---
  {
    id: 'act-12',
    agentId: 'client-intake',
    description: 'Sent intake form to new client Rachel Green',
    status: 'completed',
    creditsUsed: 1,
    timestamp: '2026-03-10T08:00:00Z',
  },
  {
    id: 'act-13',
    agentId: 'client-intake',
    description: 'Auto-populated CRM record for Rachel Green from intake form',
    detail: 'Contact info, service preferences, and pet details added to CRM',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-10T09:15:00Z',
  },
  {
    id: 'act-14',
    agentId: 'client-intake',
    description: 'New client David Kim completed intake form',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-08T15:30:00Z',
  },

  // --- Quote Builder ---
  {
    id: 'act-15',
    agentId: 'quote-builder',
    description: 'Generated quote #1847 for Johnson residence — kitchen remodel',
    detail: '$12,400 total with 6 line items, sent for e-signature',
    status: 'completed',
    creditsUsed: 5,
    timestamp: '2026-03-10T11:00:00Z',
  },
  {
    id: 'act-16',
    agentId: 'quote-builder',
    description: 'Quote #1832 opened by client — viewed 3 times',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-09T18:00:00Z',
  },
  {
    id: 'act-17',
    agentId: 'quote-builder',
    description: 'Sent follow-up on unsigned quote #1819 to Maria Lopez',
    status: 'completed',
    creditsUsed: 1,
    timestamp: '2026-03-09T10:00:00Z',
  },
  {
    id: 'act-18',
    agentId: 'quote-builder',
    description: 'Quote #1847 approved and signed — job added to calendar',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-10T15:30:00Z',
  },

  // --- Booking Assistant ---
  {
    id: 'act-19',
    agentId: 'booking-assistant',
    description: 'Booked haircut appointment for new client via Instagram DM',
    detail: 'Wednesday at 2pm with stylist Jenna — confirmed and synced to calendar',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-10T12:30:00Z',
  },
  {
    id: 'act-20',
    agentId: 'booking-assistant',
    description: 'Offered cancelled 3pm slot to 2 waitlisted clients',
    status: 'running',
    creditsUsed: 1,
    timestamp: '2026-03-10T15:00:00Z',
  },

  // --- Win-Back Campaign ---
  {
    id: 'act-21',
    agentId: 'win-back-campaign',
    description: 'Identified 5 dormant clients — no visit in 60+ days',
    detail: 'David Kim, Lisa Tran, Marco Reyes, Jen Park, Alex Nguyen',
    status: 'completed',
    creditsUsed: 1,
    timestamp: '2026-03-09T07:00:00Z',
  },
  {
    id: 'act-22',
    agentId: 'win-back-campaign',
    description: 'Sent re-engagement offer to David Kim — 15% off next service',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-09T07:30:00Z',
  },
  {
    id: 'act-23',
    agentId: 'win-back-campaign',
    description: 'Win-back conversion: Amy Chen rebooked after 45-day absence',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-08T16:00:00Z',
  },

  // --- Local SEO ---
  {
    id: 'act-24',
    agentId: 'local-seo',
    description: 'Updated Google Business Profile with 4 new service photos',
    status: 'completed',
    creditsUsed: 2,
    timestamp: '2026-03-09T06:00:00Z',
  },
  {
    id: 'act-25',
    agentId: 'local-seo',
    description: 'Local ranking for "plumber near me" improved from #5 to #3',
    detail: 'Keyword position tracking shows steady climb over last 2 weeks',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-08T06:00:00Z',
  },

  // --- Invoice & Payment ---
  {
    id: 'act-26',
    agentId: 'invoice-payment',
    description: 'Sent invoice #1042 to James Wilson — $350',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-10T13:00:00Z',
  },
  {
    id: 'act-27',
    agentId: 'invoice-payment',
    description: 'Payment received from Sarah Johnson — $275',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-10T10:30:00Z',
  },
  {
    id: 'act-28',
    agentId: 'invoice-payment',
    description: 'Sent 3-day reminder for unpaid invoice #1038 to Tom Brown',
    status: 'completed',
    creditsUsed: 1,
    timestamp: '2026-03-09T09:00:00Z',
  },
  {
    id: 'act-29',
    agentId: 'invoice-payment',
    description: 'Payment overdue: invoice #1031 to David Kim — 7 days',
    status: 'failed',
    creditsUsed: 1,
    timestamp: '2026-03-08T09:00:00Z',
    preview: [
      { label: 'Invoice', value: '#1031 — Bathroom renovation consultation' },
      { label: 'Client', value: 'David Kim · david.kim@email.com · (555) 234-5678' },
      { label: 'Amount', value: '$450.00' },
      { label: 'Due date', value: 'March 1, 2026 — 7 days overdue' },
      { label: 'Reminders sent', value: '3-day and 7-day auto-reminders sent, no response' },
    ],
  },

  // --- Referral Program ---
  {
    id: 'act-30',
    agentId: 'referral-program',
    description: 'New referral tracked: Amy Chen referred Lisa Park',
    status: 'completed',
    creditsUsed: 1,
    timestamp: '2026-03-09T12:00:00Z',
  },
  {
    id: 'act-31',
    agentId: 'referral-program',
    description: 'Sent $25 reward to Amy Chen for successful referral',
    status: 'completed',
    creditsUsed: 2,
    timestamp: '2026-03-09T12:05:00Z',
  },

  // --- Client Follow-Up ---
  {
    id: 'act-32',
    agentId: 'client-follow-up',
    description: 'Sent birthday message to Maria Lopez',
    status: 'completed',
    creditsUsed: 1,
    timestamp: '2026-03-10T07:00:00Z',
  },
  {
    id: 'act-33',
    agentId: 'client-follow-up',
    description: 'Sent post-service check-in to Tom Brown',
    detail: '"How\'s the new AC working? Let us know if you need anything."',
    status: 'completed',
    creditsUsed: 2,
    timestamp: '2026-03-09T15:00:00Z',
  },
  {
    id: 'act-34',
    agentId: 'client-follow-up',
    description: 'Sent spring HVAC tune-up reminder to 12 clients',
    status: 'completed',
    creditsUsed: 3,
    timestamp: '2026-03-08T08:00:00Z',
  },

  // --- Email Newsletter ---
  {
    id: 'act-35',
    agentId: 'email-newsletter',
    description: 'Drafted March newsletter — awaiting your approval',
    status: 'needs-approval',
    creditsUsed: 7,
    timestamp: '2026-03-10T06:00:00Z',
    preview: [
      { label: 'Subject line', value: 'Spring Is Here! Tips, News & a Special Offer Inside' },
      { label: 'Sections', value: '1. Top 5 spring cleaning tips for your home\n2. Meet Jenna, our newest team member\n3. 10% off all services through March 31' },
      { label: 'Preview text', value: '"Spring is the perfect time to refresh your home. Here are 5 quick tips our team swears by — plus a special offer just for you..."' },
      { label: 'Recipients', value: '847 active subscribers · Estimated 42% open rate based on past performance' },
    ],
  },
  {
    id: 'act-36',
    agentId: 'email-newsletter',
    description: 'February newsletter sent to 847 subscribers',
    status: 'completed',
    creditsUsed: 10,
    timestamp: '2026-03-01T10:00:00Z',
  },
  {
    id: 'act-37',
    agentId: 'email-newsletter',
    description: 'February newsletter performance: 42% open rate, 8% clicks',
    status: 'completed',
    creditsUsed: 0,
    timestamp: '2026-03-03T06:00:00Z',
  },
];

export function getAgentActivities(): AgentActivity[] {
  return activities.sort(
    (a, b) => new Date(b.timestamp).getTime() - new Date(a.timestamp).getTime(),
  );
}
